xychart-beta
    title "Code Coverage by Module (%)"
    x-axis ["delete_api", "app", "getfilters", "GroupingHandler", "DeleteHandler", "BaseHandler", "TokenRefresher", "Scheduler", "EmailFetcher", "logger", "BounceHandler", "EmailCurator", "env / utils"]
    y-axis "Coverage %" 0 --> 100
    bar [0, 0, 38, 60, 67, 75, 76, 79, 81, 87, 91, 97, 100]
